### ISSUE TITLE
Raft WSL cannot update the distros (Pengwin, ubuntu, Pengwin Enterprise) while a VPN is enabled

### ISSUE THREAD

**Issue by Jack31071973** [WhitewaterFoundry/Raft-WSL-Feedback#19]
Raft WSL cannot update the distros (Pengwin, ubuntu, Pengwin Enterprise) while a VPN is enabled. I do not know if the problem is in Raft WSL or Distros or Windows WSL, but if VPN is enabled, you will not be able to update/upgrade distros. The problem should be on the Windows WSL side because I cannot update even from the command line using apt or yum.

**Edition**: Windows 10 Pro for Workstations
**Version**: 21H1
**OS build**:	19043.1320
**Experience**: Windows Feature Experience Pack 120.2212.3920.0

VPN: Hotspot Shield (Premium).

  Fill free to close it if the problem is not in Raft.

**Comment by crramirez** [comment]
Hello @Jack31071973

It is a problem with WSL2 and the VPNs. They have added support for major ones but there are too many still that present problems.

With most of them the problem is the dns. You can solve it hardcoding the resolv.conf in tour distro and tell it do not overwrite it in /etc/wsl.conf.

Later I'll post here a link with the information and the related issue.

Regards,
Carlos

**Comment by crramirez** [comment]
@Jack31071973 

This is a good guide for VPN and WSL2: https://gist.github.com/pyther/b7c03579a5ea55fe431561b502ec1ba8
