### ISSUE TITLE
WSL Default version won't stay on 2

### ISSUE THREAD

**Issue by jcousino** [WhitewaterFoundry/Raft-WSL-Feedback#33]
Changes to version 1 even if changed from settings.

**Comment by crramirez** [comment]
It can happen in a newly installed system with just the Store version installed. If it is the case run once `wsl --set-default-version 2` and check the output?

If WSL2 is not correctly installed you'll see it with the above command.

Or can be a regression. Can you please confirm me the following?

* Your windows build version
* Raft version (From Settings)
* `wsl --version` output
* `wsl --status` output
* Windows default language (yes this is important because the wsl command output is localized

Thanks for reporting

**Comment by crramirez** [comment]
Hello @jcousino,

We identified the problem. Thanks for reporting, expect soon the version 23.5.2 with the fix.

We apologize for the inconvenience caused.

Regards,
Carlos

**Comment by crramirez** [comment]
The version with the fix is now live in the Microsoft Store

**Comment by jcousino** [comment]
Thank you...works perfectly again.

Jeff
