### ISSUE TITLE
I always get this message on Raft "Raft is receiving the WSL command with delay ...."

### ISSUE THREAD

**Issue by Jack31071973** [WhitewaterFoundry/Raft-WSL-Feedback#40]
I always get this message on Raft "Raft is receiving the WSL command with delay ...." shutdown WSL and restart it does not have any effect, the message will appear again.

**Comment by crramirez** [comment]
This message can appear during a backup or a lengthy operation; a corrected version will be delivered soon.

But if it happens to you recurrently, it is because there is a slowdown with the `wsl` command. I recommend keeping it updated; they have corrected many of those issues recently.

Anyway, the message will stop appearing in the newer releases because it causes more confusion than it helps.

**Comment by Jack31071973** [comment]
Thanks.

**Comment by crramirez** [comment]
Fixed in version 24.08.1, it won't show you the message and I will manage the delays in a better way
