### ISSUE TITLE
Raft WSL on a Dev PC and Notebook - on the Notebook hanging on activating forever

### ISSUE THREAD

**Issue by jiripik** [WhitewaterFoundry/Raft-WSL-Feedback#43]
I have purchased the product for my Dev PC. When I open it on my laptop, it asks me to activate the trial for the product and hangs forever on activating. How to fix?

**Comment by crramirez** [comment]
Hello @jiripik

This is because Raft is having problems communicating with the store. It usually get fixed restarting the laptop. By any chance your laptop is a corporate one? If this is the case the store can be blocked, try to start it without the vpn and from your home internet.

And be sure that you are using the same Microsoft account.

Best

**Comment by jiripik** [comment]
Yeah, reboot solved this. Thanks for your help!
